services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: miniops
      POSTGRES_USER: miniops
      POSTGRES_PASSWORD: miniops
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U miniops -d miniops"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://miniops:miniops@db:5432/miniops
      SECRET_KEY: change-this-before-public-release
      CORS_ORIGINS: http://localhost:5173
      REDIS_URL: redis://redis:6379/0
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      MAIL_FROM: miniops@localhost
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8000:8000"

  worker:
    build: ./backend
    command: ["python","-m","app.worker"]
    environment:
      DATABASE_URL: postgresql+psycopg://miniops:miniops@db:5432/miniops
      SMTP_HOST: mailpit
      SMTP_PORT: 1025
      MAIL_FROM: miniops@localhost
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started

  web:
    build: ./frontend
    depends_on:
      - api
    ports:
      - "5173:80"

  mailpit:
    image: axllent/mailpit:v1.21
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
